- hosts: all
  tasks:
    - copy:
        src: hostnames.conf
        dest: /etc/hosts.1
        owner: root
        group: root
        mode: 0644
    - command: /bin/bash -c "cat /etc/hosts.1 >> /etc/hosts"


      
